use_frameworks!

target 'PNPullToRefresh_Example', :exclusive => true do
  pod 'PNPullToRefresh', :path => '../'
end

target 'PNPullToRefresh_Tests', :exclusive => true do
  pod 'PNPullToRefresh', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
