platform :ios, '9.0'

target 'PNPullToRefresh_Example' do
  pod 'PNPullToRefresh', :path => '../'
end

target 'PNPullToRefresh_Tests' do
  pod 'PNPullToRefresh', :path => '../'
  pod 'Specta'
  pod 'Expecta'
end
